### PR TITLE
refactor: deploy bytecode

### LINKED ISSUE #115: allow to provide arbitrary bytecode for deployment
in my case I have pre-compiled bytecode which I want to deploy using an active SH wallet connection without having to build my own UI just for doing this.

### PR DESCRIPTION
**Pull request by thepiwo**
closes #115

### CODE REVIEW

**Comment by marc0olo** [comment]
@thepiwo currently I need to compile "something" first before I can provide the actual bytecode. is this intended?

image

**Comment by marc0olo** [comment]
and I think you need to remove the arguments verification if bytecode only is provided 🤔

**Comment by thepiwo** [comment]
yes, the idea is that you can change the bytecode to whatever you like, having it otherwise is a bigger refactoring

**Comment by thepiwo** [comment]
> and I think you need to remove the arguments verification if bytecode only is provided 🤔

I think this happens based on the ACI, which does need to be provided in order to interact anyways

**Comment by marc0olo** [comment]
> I think this happens based on the ACI, which does need to be provided in order to interact anyways

there still seems to be an argument check somehow at this point if we "wipe out" the ACI input. something relies on the compiled output and I need to compile "something" in order to be able to see the bytecode input field. as a workaround I could compile some contract that matches the numbers of arguments. but it would be better to not rely on that at all.

still, I would be able to achieve what I want with some minor workaround.

note: keeping the "default" or some "invalid" (non-matching arguments) source code compilation and just replacing the ACI with the actual ACI that matches the custom bytecode, does NOT work

**Review by marc0olo — APPROVED** [review]
@thepiwo I just accidentially provided a string argument with quotations when testing the deployment. I opened an issue for that: https://github.com/aeternity/aepp-contracts/issues/118

other than that it works perfect, thanks! 🙏

**Pull request merged**
